[package]
name = "oskar"
version = "0.1.0"
authors = ["Ramsey Nasser <ram@nas.sr>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
clap = "3.0.0-beta.2"

[dependencies.python-parser]
version = "0.2.0"
default-features = false