[package]
name = "oskar"
version = "4.0.0"
authors = ["Ramsey Nasser <ram@nas.sr>"]
edition = "2018"

[dependencies]
pest = "2.6.0"
pest_derive = "2.6.0"
clap = "3.0.0-beta.2"
regex = "*"
normalize-line-endings = "*"

[dependencies.python-parser]
version = "0.2.0"
default-features = false