[tasks.linux]
command = "cargo"
env = { "PYO3_CROSS_PYTHON_VERSION" = "3.11" }
args = ["build", "--release"]

[tasks.windows]
command = "cargo"
env = { "PYO3_CROSS_PYTHON_VERSION" = "3.11" }
args = ["build", "--target", "x86_64-pc-windows-gnu", "--release"]

[tasks.all]
dependencies = ["linux", "windows"]

# [tasks.render-test]
# dependencies = ["linux"]
# script = """
# for file in render_cases/*; do
#     ./target/release/oskar compile $file > $file.out.py
#     mkdir $file.out-frames
#     blender -b -E BLENDER_WORKBENCH -P $file.out.py -o $file.out-frames/frame -F JPEG -x 1 -a
#     ffmpeg -r 60 -i $file.out-frames/frame%04d.jpg -vcodec libx264 -crf 25 -pix_fmt yuv420p $file.mp4
#     rm -fr $file.out-frames
#     rm $file.out.py
# done
# version=`git describe --tags --abbrev=0`
# mkdir -p render_out/$version/
# mv render_cases/*.mp4 render_out/$version/
# """

[tasks.version-bump]
script = """
new_tag=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; printf("%d.%04d", $1, $2)}'`
git tag $new_tag
"""

[tasks.changelog]
script = """
echo -n "" > changes.txt
most_recent_tag=`git describe --abbrev=0 --tags`
commits=`git rev-list $most_recent_tag..HEAD`
for commit in $commits
do
    message=`git log --pretty=format:"- %s (%as, %h)" -n 1 $commit`
    if [[ $message != *chore* ]]; then
        echo $message >> changes.txt
    fi
done
"""

[tasks.deliver]
dependencies = ["changelog", "version-bump", "all"]
script = """
tag=`git describe --tags --abbrev=0`
source="target/x86_64-pc-windows-gnu/release/oskar.exe"
destination="/home/nasser/Dropbox/Oskar Project/Oskar/System04/$tag/"
mkdir -p "$destination"
cp "$source" "$destination"
mv changes.txt "$destination"
echo "delivered $tag to $destination"
"""
