name: Nightly Builds

on:
  push:
    branches: [ v3 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Linux Build
      run: cargo build --verbose --release
    - name: Windows Build
      run: cargo build --verbose --release --target x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
